# Generated by Django 2.0.7 on 2018-07-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('age', models.IntegerField(db_column='Age')),
                ('sex', models.CharField(db_column='Sex', max_length=10)),
                ('is_friendly', models.NullBooleanField(db_column='Is_friendly_with_cats?')),
                ('image_url', models.URLField(db_column='Image_URL')),
            ],
        ),
    ]
