# Generated by Django 2.0.7 on 2018-07-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20180707_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='is_friendly',
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.CharField(db_column='Age', max_length=20),
        ),
    ]
