# Generated by Django 2.0.7 on 2018-07-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20180710_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(db_column='Name', max_length=40),
        ),
    ]
