# Generated by Django 2.0.7 on 2018-07-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20180712_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image_url',
            field=models.URLField(db_column='Image_URL'),
        ),
    ]
